apiVersion: v1
kind: Service
metadata:
  name: gta1-vllm
  namespace: gta1
  labels:
    app: gta1-vllm
spec:
  type: ClusterIP
  selector:
    app: gta1-vllm
  ports:
  - name: http
    port: 8000
    targetPort: http
