apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-cache
  namespace: gta1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: standard
